sudo: false
language: ruby
cache: bundler
rvm: 2.6
script:
- bundle exec jekyll build

after_success:
- openssl aes-256-cbc -K $encrypted_cf4b5eaade1a_key -iv $encrypted_cf4b5eaade1a_iv
  -in .deploy_key.enc -out .deploy_key -d
- eval "$(ssh-agent -s)"
- ssh-add -D
- chmod 600 .deploy_key
- ssh-add .deploy_key
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
