language: ruby
cache: bundler
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
before_install:
- openssl aes-256-cbc -K $encrypted_cf4b5eaade1a_key -iv $encrypted_cf4b5eaade1a_iv
  -in .deploy_key.enc -out .deploy_key -d
- chmod 600 .deploy_key
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
