# Site settings
title: halleluja.nu
email: per@halleluja.nu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://halleluja.nu" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet

permalink:        pretty

category_archive:
  slugify:        true

gems:
  - jemoji

exclude: [vendor]
